### PR TITLE
fix for use with QT gui

### LINKED ISSUE #2: Seems like this has been broken for a while
I'm still running into the issue described here: https://github.com/supercollider/supercollider/issues/296

### PR DESCRIPTION
**Pull request by dyfer**
Fixes #2.

Not sure who'd like to look at this and merge? @snappizz ? @jamshark70 ? Thanks!

### CODE REVIEW

**Comment by jamshark70** [comment]
That's all that was needed? :laughing: I'm in transit now but I don't mind to check it over a bit later.

**Comment by dyfer** [comment]
Thanks!
> That's all that was needed? 😆 

Yes! It looks like everyone at SC is doing a pretty good job in keeping the API stable! 👍
Feel free to also review/merge the helpfile PR :) Thanks again!

**Comment by jamshark70** [comment]
Behaves as advertised :+1:

**Comment by machty** [comment]
Thank you so much!

**Pull request merged**
